<?php
/**
 * Redux Settings
 *
 * @package MellowTheme
 * @version 1.0.0
 */
// Exit if accessed directly
defined( 'ABSPATH' ) || exit;

Redux::set_section(
	$opt_name,
	array(
		'title'      => esc_html__( 'Footer Typography', 'mellow' ),
		'id'         => 'mellow_footer_typography_settings',
        'icon'       => 'dashicons dashicons-arrow-right-alt',
		'subsection' => true,
		'fields'     => array(
            array(
				'id'                => 'mellow_footer_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'Font', 'mellow' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => false,
				'letter-spacing'    => true,
                'font-size'         => true,
                'line-height'       => true,
				'text-transform'    => true,
                'units'             => 'px',
				'output'            => array( '.dtr-footer-section-wrap' ),
			),
            array(
				'id'       => 'mellow_footer_link',
				'type'     => 'link_color',
                'title'    => esc_html__( 'Link Color', 'mellow' ),
                'active'   => false,
				'output'   => array( '.dtr-footer-section-wrap a' ),
			),
            // h1
            array(
				'id'    => 'mellow_info_footer_headings',
				'type'  => 'info',
                'title' => esc_html__( 'Headings in Footer', 'mellow' ),
			),
            array(
				'id'                => 'mellow_footer_h1_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'H1', 'mellow' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => true,
				'letter-spacing'    => true,
                'font-size'         => true,
                'line-height'       => true,
				'text-transform'    => true,
                'units'             => 'px',
				'output'            => array( '.dtr-footer-section-wrap h1' ),
			),
            array(
				'id'                => 'mellow_footer_h2_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'H2', 'mellow' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => true,
				'letter-spacing'    => true,
                'font-size'         => true,
                'line-height'       => true,
				'text-transform'    => true,
                'units'             => 'px',
				'output'            => array( '.dtr-footer-section-wrap h2' ),
			),
            array(
				'id'                => 'mellow_footer_h3_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'H3', 'mellow' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => true,
				'letter-spacing'    => true,
                'font-size'         => true,
                'line-height'       => true,
				'text-transform'    => true,
                'units'             => 'px',
				'output'            => array( '.dtr-footer-section-wrap h3' ),
			),
            array(
				'id'                => 'mellow_footer_h4_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'H4', 'mellow' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => true,
				'letter-spacing'    => true,
                'font-size'         => true,
                'line-height'       => true,
				'text-transform'    => true,
                'units'             => 'px',
				'output'            => array( '.dtr-footer-section-wrap h4' ),
			),
            array(
				'id'                => 'mellow_footer_h5_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'H5', 'mellow' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => true,
				'letter-spacing'    => true,
                'font-size'         => true,
                'line-height'       => true,
				'text-transform'    => true,
                'units'             => 'px',
				'output'            => array( '.dtr-footer-section-wrap h5' ),
			),
            array(
				'id'                => 'mellow_footer_h6_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'H6', 'mellow' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => true,
				'letter-spacing'    => true,
                'font-size'         => true,
                'line-height'       => true,
				'text-transform'    => true,
                'units'             => 'px',
				'output'            => array( '.dtr-footer-section-wrap h6' ),
			),
            array(
				'id'   => 'mellow_info_copyright_typo',
				'type' => 'info',
                'title' => esc_html__( 'Copyright', 'mellow' ),
			),
            array(
				'id'                => 'mellow_copyright_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'Font', 'mellow' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => false,
				'letter-spacing'    => true,
                'font-size'         => true,
                'line-height'       => true,
				'text-transform'    => true,
                'units'             => 'px',
				'output'            => array( '.dtr-footer-section-wrap .dtr-copyright' ),
			),
            array(
				'id'       => 'mellow_copyright_link',
				'type'     => 'link_color',
                'title'    => esc_html__( 'Link Color', 'mellow' ),
                'active'   => false,
				'output'   => array( '.dtr-footer-section-wrap .dtr-copyright a' ),
			),
           array(
				'id'   => 'mellow_info_footer_button',
				'type' => 'info',
                'title' => esc_html__( 'Button in Footer', 'mellow' ),
			),
           array(
				'id'       => 'mellow_footerbtn_color',
				'type'     => 'link_color',
                'title'    => esc_html__( 'Font Color', 'mellow' ),
                'active'   => false,
				'output'   => array( '.dtr-footer-section-wrap  .wp-block-button__link' ),
			),
            array(
				'id'          => 'mellow_footerbtn_bg',
				'type'        => 'color',
				'title'       => esc_html__( 'Background Color', 'mellow' ),
				'default'     => '',
				'transparent' => false,
				'validate'    => 'color',
				'output'      => array(
					'background-color' => '.dtr-footer-section-wrap  .wp-block-button__link',
				),
			),
            array(
				'id'          => 'mellow_footerbtn_hover_bg',
				'type'        => 'color',
				'title'       => esc_html__( 'Hover: Background Color', 'mellow' ),
				'default'     => '',
				'transparent' => false,
				'validate'    => 'color',
				'output'      => array(
					'background-color' => '.dtr-footer-section-wrap  .wp-block-button__link:hover',
				),
			),
		),
	)
);